[env:waveshare-s3-lcd43]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
build_flags =
    -Iinclude
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_LVGL_H_INCLUDE_SIMPLE
lib_deps =
    lvgl/lvgl@^8.3.11
    lovyan03/LovyanGFX@^1.1.16
    plerup/EspSoftwareSerial@^8.1.0
